ALTER TABLE affordability_checks
ADD COLUMN IF NOT EXISTS target_date TEXT,
ADD COLUMN IF NOT EXISTS calculated_at TEXT,
ADD COLUMN IF NOT EXISTS monthly_income NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS monthly_expenses NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS monthly_surplus NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS funding_gap NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS months_until_target INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS required_monthly_saving NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS active_goal_commitments NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS available_after_goals NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS expense_period TEXT NOT NULL DEFAULT '';
